name: Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prep
        run: |
          echo ::set-output name=commitSHA::$(git rev-parse --short HEAD)
      -
        name: Setup BuildX
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/d3vd/meme_api:latest
            ghcr.io/d3vd/meme_api:${{ steps.prep.outputs.commitSHA }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
